<a href="https://colab.research.google.com/github/AimanIqbal-sys/data-science-w1/blob/library%2Fnumpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array of size 2 x 2

In [17]:
import numpy as np

print("--- 1. 2x2 Array ---")
arr_2x2 = np.array([[1, 2],
                    [3, 4]])
print(arr_2x2)
print("Shape:", arr_2x2.shape)

--- 1. 2x2 Array ---
[[1 2]
 [3 4]]
Shape: (2, 2)


2. Create a random numpy array of size 3 x 4

In [18]:
print("--- 2. 3x4 Random Array ---")
arr_3x4_random = np.random.rand(3, 4)
print(arr_3x4_random)
print("Shape:", arr_3x4_random.shape)

--- 2. 3x4 Random Array ---
[[0.79706807 0.16733515 0.93146269 0.73888462]
 [0.38230125 0.14770591 0.31120978 0.84294951]
 [0.87583727 0.86740574 0.67984122 0.91427232]]
Shape: (3, 4)


3. Create a numpy array of ones and a numpy array of zeroes

In [19]:
print("--- 3. Ones and Zeros Arrays (e.g., 2x3) ---")
arr_ones = np.ones((2, 3))
print("Ones:")
print(arr_ones)

arr_zeros = np.zeros((2, 3))
print("\nZeros:")
print(arr_zeros)

--- 3. Ones and Zeros Arrays (e.g., 2x3) ---
Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [22]:
print("--- 4. Transposed 6x3 Array ---")
arr_6x3 = np.random.rand(6, 3)
print("Original 6x3:")
print(arr_6x3)

arr_transposed = arr_6x3.T
print("\nTransposed (now 3x6):")
print(arr_transposed)
print("Original shape:", arr_6x3.shape)
print("Transposed shape:", arr_transposed.shape)

--- 4. Transposed 6x3 Array ---
Original 6x3:
[[0.05007    0.28227732 0.69777875]
 [0.56900657 0.76634205 0.10461989]
 [0.72446441 0.56578042 0.77680961]
 [0.09808226 0.62111002 0.95811061]
 [0.68989155 0.68175814 0.20678649]
 [0.86850842 0.5861834  0.20989666]]

Transposed (now 3x6):
[[0.05007    0.56900657 0.72446441 0.09808226 0.68989155 0.86850842]
 [0.28227732 0.76634205 0.56578042 0.62111002 0.68175814 0.5861834 ]
 [0.69777875 0.10461989 0.77680961 0.95811061 0.20678649 0.20989666]]
Original shape: (6, 3)
Transposed shape: (3, 6)


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [24]:
print("--- 5. Dot Product of n x p and p x m ---")
n = 4
p = 3
m = 5

print(f"Creating A (n x p = {n}x{p}) and B (p x m = {p}x{m})")
A = np.random.rand(n, p)
B = np.random.rand(p, m)
C_dot_product = A @ B
print("A:")
print(A)
print("B:")
print(B)
print("\nDot Product (C = A @ B):")
print(C_dot_product)
print("Resulting shape (n x m):", C_dot_product.shape)

--- 5. Dot Product of n x p and p x m ---
Creating A (n x p = 4x3) and B (p x m = 3x5)
A:
[[0.97956518 0.52031862 0.28557167]
 [0.06163156 0.82793248 0.97030677]
 [0.05756244 0.91992617 0.98636678]
 [0.41715824 0.56852731 0.04181713]]
B:
[[0.80719638 0.18208601 0.19851294 0.74900295 0.37924633]
 [0.79143668 0.31168508 0.02965286 0.52735799 0.93185268]
 [0.15094643 0.59314412 0.27277401 0.17793988 0.0270435 ]]

Dot Product (C = A @ B):
[[1.24560673 0.50992582 0.28778183 1.05890597 0.86407966]
 [0.85146925 0.84480821 0.3014597  0.6554353  0.82112514]
 [0.92341605 0.88226623 0.30776055 0.70375883 0.90574083]
 [0.79299413 0.27796374 0.1110764  0.6197111  0.68912032]]
Resulting shape (n x m): (4, 5)
